FROM node:lts-alpine AS BUILD
WORKDIR /app
COPY . /app
RUN npm install
RUN npx webpack --mode=production --progress -c ./webpack.config.js

FROM nginx:alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


