FROM node:16 as build
WORKDIR /app

COPY package.json ./
RUN npm install --verbose

COPY . .
RUN npx webpack --mode=production --progress -c ./webpack.config.js

FROM nginx:alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


