FROM node:18 as build
WORKDIR /app

COPY . .

WORKDIR /app/JsonSchemaEditor
RUN npm install
RUN npx webpack --mode=production --progress -c ./webpack.config.js

WORKDIR /app/CodeDiagram
RUN npm install
RUN npx webpack --mode=production --progress -c ./webpack.config.js


FROM nginx:alpine
COPY --from=build /app/CodeDiagram/dist/ /usr/share/nginx/html/CodeDiagram
COPY --from=build /app/JsonSchemaEditor/dist/ /usr/share/nginx/html/JsonSchemaEditor

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]