export type TMonacoLanguage =
    "css" |
    "html" |
    "json" |
    "typescript" |
    "abap" |
    "apex" |
    "azcli" |
    "bat" |
    "bicep" |
    "cameligo" |
    "clojure" |
    "coffee" |
    "cpp" |
    "csharp" |
    "csp" |
    "cypher" |
    "dart" |
    "dockerfile" |
    "ecl" |
    "elixir" |
    "flow9" |
    "freemarker2" |
    "fsharp" |
    "go" |
    "graphql" |
    "handlebars" |
    "hcl" |
    "ini" |
    "java" |
    "javascript" |
    "julia" |
    "kotlin" |
    "less" |
    "lexon" |
    "liquid" |
    "lua" |
    "m3" |
    "markdown" |
    "mdx" |
    "mips" |
    "msdax" |
    "mysql" |
    "objective-c" |
    "pascal" |
    "pascaligo" |
    "perl" |
    "pgsql" |
    "php" |
    "pla" |
    "postiats" |
    "powerquery" |
    "powershell" |
    "protobuf" |
    "pug" |
    "python" |
    "qsharp" |
    "r" |
    "razor" |
    "redis" |
    "redshift" |
    "restructuredtext" |
    "ruby" |
    "rust" |
    "sb" |
    "scala" |
    "scheme" |
    "scss" |
    "shell" |
    "solidity" |
    "sophia" |
    "sparql" |
    "sql" |
    "st" |
    "swift" |
    "systemverilog" |
    "tcl" |
    "twig" |
    "typespec" |
    "vb" |
    "wgsl" |
    "xml" |
    "yaml" |
    "groovy"