name: Github_GHCR

on:
  push:
    branches:
      - dev
      - desenv01

jobs:
  start-main:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
      DOCKER_HUB_USER: ${{secrets.DOCKER_HUB_USER}}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login Dockerhub
        run: echo "${{ env.DOCKER_HUB_TOKEN }}" | docker login -u ${{env.DOCKER_HUB_USER}} --password-stdin

      - name: Build imageg and push in dockerhub
        run: |
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.base_ref}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.event}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.event_name}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.event_path}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.run_number}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.ref_type}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.ref_name}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.ref}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.path}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.action_repository}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.action_ref}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.action_path}}"
          echo ">>>>>>>>>>>>>>>>>>>>>> ${{github.action}}"



