name: Update LocalWeb VM

on:
    push:
        branches:
          - dev
    pull_request:
        branches:
          - main
jobs:
    start-main:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18.18.0'
            - name: Install dependencies
              run: npm install
        
            - name: RUN WEBPACK
              run: npx webpack --mode=production
    update-dev-env:
      needs: start-main
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      steps:
        - name: log
          run: |
              echo 'dev'
              ls
    update-prod-env:
      needs: start-main
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      steps:
        - name: log
          run: |
              echo 'prod'
              ls