name: Update LocalWeb VM

on:
    push:
        branches:
          - dev
    pull_request:
        branches:
          - main
jobs:
    start-main:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18.18.0'
            - name: Install dependencies
              run: npm install
        
            - name: RUN WEBPACK
              #run: npx webpack --mode=production
              run: npx webpack --mode=development

            - name: UPLOAD DIST
              uses: actions/upload-artifact@v2
              with:
                name: finalDist
                path: src/dist*


    update-dev-env:
      needs: start-main
      runs-on: ubuntu-latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      env:
        SSH_USERNAME: ${{ secrets.LW_VM001_USER_NAME }}
        SSH_PASSWORD: ${{ secrets.LW_VM001_USER_PASSD }}
        VM_IP: ${{ vars.LOCAL_WEB_IP_VM_001 }}
        VM_DEV_PATH: ${{ vars.LOCAL_WEB_DEV_PATH_MV_001 }}

      steps:
        - name: Download DIST
          uses: actions/download-artifact@v2
          with:
           name: finalDist
        
        - name: log
          run: |
               echo echo $(ls dist)

        - name: Install sshpass
          run: sudo apt-get install -y sshpass
           
        - name: remove current dist
          run: |
           sshpass -p ${{env.SSH_PASSWORD}} ssh ${{env.SSH_USERNAME}}@${{env.VM_IP}}
           ssh ${{env.SSH_USERNAME}}@${{env.VM_IP}} "ls"

    update-prod-env:
      needs: start-main
      runs-on: ubuntu-latest
      if: github.event_name == 'pull_request' && github.base_ref == 'main'
      steps:
        - name: log
          run: |
              echo 'prod'
              echo echo $(ls)