name: Update LocalWeb VM

on:
    push:
        branches:
          - dev

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18.18.0'
            - name: Install dependencies
              run: npm install
        
            - name: RUN WEBPACK
              run: npx webpack --mode=production

            # - name: print out example job
            #   uses: appleboy/ssh-action@v0.1.10
            #   env:
            #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_LOCAL_WEB_VM001 }}
            #     VM_IP: ${{ vars.LOCAL_WEB_IP_VM_001 }}
            #     VM_USER: ${{ vars.LOCAL_WEB_USER_MV_001 }}
            #     VM_PATH: ${{ vars.LOCAL_WEB_DEV_PATH_MV_001 }}
            #     VM_PORT: ${{ vars.LOCAL_WEB_PORT_MV_001 }}
            #   with:
            #     host: ${{ env.VM_IP }}
            #     username: ${{ env.VM_USER }}
            #     key: ${{ env.SSH_PRIVATE_KEY }}
            #     port: ${{ env.LOCAL_WEB_PORT_MV_001 }}
            #     command_timeout: 30m
            #     script: | 
            #       echo "Nice Job!!!"



            
            - name: UPDATE LOCAL WEB VM001
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_LOCAL_WEB_VM001 }}
                VM_IP: ${{ vars.LOCAL_WEB_IP_VM_001 }}
                VM_USER: ${{ vars.LOCAL_WEB_USER_MV_001 }}
                VM_PATH: ${{ vars.LOCAL_WEB_DEV_PATH_MV_001 }}
              run: |
                mkdir -p ~/.ssh
                echo "${{ env.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ env.VM_IP }} >> ~/.ssh/known_hosts
                rm -r ${{ env.VM_PATH }}*
                scp -o StrictHostKeyChecking=no -r dist/* ${{ env.VM_USER }}@${{ env.VM_IP }}:${{ env.VM_PATH }}