name: Update LocalWeb VM

on:
    push:
        branches:
          - dev
    pull_request:
        branches:
          - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '18.18.0'
            - name: Install dependencies
              run: npm install
        
            - name: RUN WEBPACK
              run: npx webpack --mode=production

            - name: Definir ambiente
              id: set_env_vars
              run: |
                if [ "${{ github.ref == 'refs/heads/main' }}" = "true" ]; then
                  echo "VM_PATH=$LOCAL_WEB_PROD_PATH_MV_001" >> $GITHUB_ENV
                else
                  echo "VM_PATH=$LOCAL_WEB_DEV_PATH_MV_001" >> $GITHUB_ENV
                fi

            - name: UPDATE LOCAL WEB VM001
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_LOCAL_WEB_VM001 }}
                VM_IP: ${{ vars.LOCAL_WEB_IP_VM_001 }}
                VM_USER: ${{ vars.LOCAL_WEB_USER_MV_001 }}
                VM_PATH: ${{ steps.set_env_vars.outputs.VM_PATH }}
              run: |
                mkdir -p ~/.ssh
                echo "${{ env.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan -H ${{ env.VM_IP }} >> ~/.ssh/known_hosts
                ssh ${{ env.VM_USER }}@${{ env.VM_IP }} "rm -r ${{ env.VM_PATH }}/*"
                scp -o StrictHostKeyChecking=no -r dist/* ${{ env.VM_USER }}@${{ env.VM_IP }}:${{ env.VM_PATH }}